<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="factors" nsURI="http://www.example.org/kindness_metamodel_factors"
    nsPrefix="kindness_metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="AbsSocialFactors" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" eType="#//AbsKindnessEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="socialfactor" upperBound="-1"
        eType="#//Social/SocialFactor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbsKindnessEntity" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Factor" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedfactor" upperBound="-1"
        eType="#//AffectedFactor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DegreeOfRelatedness">
    <eLiterals name="FAMILY"/>
    <eLiterals name="FRIEND" value="1"/>
    <eLiterals name="COLLEAGUE" value="2"/>
    <eLiterals name="ACQUAINTANCE" value="3"/>
    <eLiterals name="STRANGER" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Need">
    <eLiterals name="EMOTIONAL"/>
    <eLiterals name="INSTRUMENTAL" value="1"/>
    <eLiterals name="HEALTH_RELATED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Opportunity">
    <eLiterals name="MAKE_NEW_FRIEND"/>
    <eLiterals name="KEEP_OLD_FRIEND" value="1"/>
    <eLiterals name="STRENGTHEN_FAMILY_TIES" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Level">
    <eLiterals name="HIGH"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="LOW" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbsPsychologicalFactors" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FactorImpact">
    <eLiterals name="POSITIVE"/>
    <eLiterals name="NEGATIVE" value="1"/>
    <eLiterals name="NONE" value="2"/>
    <eLiterals name="UNKNOWN" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AffectedFactor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="factor" eType="#//Factor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impact" eType="#//FactorImpact"/>
  </eClassifiers>
  <eSubpackages name="Social" nsURI="http://www.example.org/kindness_metamodel_factors_social"
      nsPrefix="package_socialfactors">
    <eClassifiers xsi:type="ecore:EClass" name="LevelOfNeed" eSuperTypes="#//Social/SocialFactor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="need" eType="#//Need"
          defaultValueLiteral="EMOTIONAL"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//Level"
          defaultValueLiteral="MEDIUM"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Relatedness" eSuperTypes="#//Social/SocialFactor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="degree" eType="#//DegreeOfRelatedness"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reciprocity" eSuperTypes="#//Social/SocialFactor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReciprocal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SocialFactor" abstract="true" eSuperTypes="#//Factor">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actor" lowerBound="1"
          eType="#//AbsKindnessEntity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OpportunityToConnect" eSuperTypes="#//Social/SocialFactor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opportunity" eType="#//Opportunity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Trust" eSuperTypes="#//Social/SocialFactor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//Level"
          defaultValueLiteral="MEDIUM"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
